improve purgepackages

diff --git a/purgepackages b/purgepackages
--- a/purgepackages
+++ b/purgepackages
@@ -1,3 +1,9 @@
 #!/bin/sh
-# purge packages wich removed but not purged
-dpkg -l | grep ^rc | cut -d' ' -f3| sudo xargs dpkg -P
+# purge packages which are removed but not purged
+DPKG_CMD=$(which dpkg 2>/dev/null)
+if [ -n "$DPKG_CMD" ]; then
+  dpkg -l | grep ^rc | cut -d' ' -f3| sudo xargs dpkg -P
+else
+  echo "Error: no deb-base distribution; cannot purge packages!"
+  exit 1
+fi
